//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillUp_HCI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odgovori
    {
        public int OdgovorID { get; set; }
        public string Odgovor { get; set; }
        public bool Tacan { get; set; }
        public int PitanjeID { get; set; }
    
        public virtual Pitanje Pitanje { get; set; }
    }
}
